// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortionWise.Database;

#nullable disable

namespace PortionWise.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240813034203_CapitalisePortionSize")]
    partial class CapitalisePortionSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PortionWise.Models.Ingredient.Entities.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PortionWise.Models.Nutrition.Entity.NutritionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CacheExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbohydratesTotalGram")
                        .HasColumnType("REAL");

                    b.Property<double>("CholesterolMg")
                        .HasColumnType("REAL");

                    b.Property<double>("FatSaturatedGram")
                        .HasColumnType("REAL");

                    b.Property<double>("FatTotalGram")
                        .HasColumnType("REAL");

                    b.Property<double>("FiberGram")
                        .HasColumnType("REAL");

                    b.Property<double>("PotassiumMg")
                        .HasColumnType("REAL");

                    b.Property<double>("ProteinGram")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ServingSize")
                        .HasColumnType("REAL");

                    b.Property<double>("SodiumMg")
                        .HasColumnType("REAL");

                    b.Property<double>("SugarGram")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("NutritionInfo");
                });

            modelBuilder.Entity("PortionWise.Models.Recipe.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortionSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PortionWise.Models.Ingredient.Entities.IngredientEntity", b =>
                {
                    b.HasOne("PortionWise.Models.Recipe.Entities.RecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PortionWise.Models.Nutrition.Entity.NutritionEntity", b =>
                {
                    b.HasOne("PortionWise.Models.Recipe.Entities.RecipeEntity", "Recipe")
                        .WithMany("NutritionInfo")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PortionWise.Models.Recipe.Entities.RecipeEntity", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("NutritionInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
